from django.db import models
from django.db.models.fields import DateTimeField

# Create your models here.
class Winner(models.Model):
    day = models.CharField(max_length=10)
    date = models.DateField(null=False)
    winner = models.CharField(max_length=100,null=True)
    draw_time = models.CharField(max_length=10, null=True)
    w1 = models.IntegerField(null=True)
    w2 = models.IntegerField(null=True)
    w3 = models.IntegerField(null=True)
    w4 = models.IntegerField(null=True)
    w5 = models.IntegerField(null=True)
    w6 = models.IntegerField(null=True)
    w7 = models.IntegerField(null=True)
    w8 = models.IntegerField(null=True)
    w9 = models.IntegerField(null=True)
    w10 = models.IntegerField(null=True)
    w11 = models.IntegerField(null=True)
    w12 = models.IntegerField(null=True)
    w13 = models.IntegerField(null=True)
    w14 = models.IntegerField(null=True)
    w15 = models.IntegerField(null=True)
    w16 = models.IntegerField(null=True)
    w17 = models.IntegerField(null=True)
    w18 = models.IntegerField(null=True)
    w19 = models.IntegerField(null=True)
    w20 = models.IntegerField(null=True)
    created_on = DateTimeField(auto_now_add=True)