# Generated by Django 3.2.4 on 2021-06-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0002_auto_20210609_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='date',
            field=models.DateField(),
        ),
    ]
