# Generated by Django 3.2.4 on 2021-06-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0003_alter_winner_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='w11',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='w12',
        ),
        migrations.RemoveField(
            model_name='winner',
            name='w13',
        ),
        migrations.AlterField(
            model_name='winner',
            name='w1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w14',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w15',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w16',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w17',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w18',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w19',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w20',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w7',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w8',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='w9',
            field=models.IntegerField(null=True),
        ),
    ]
