# Generated by Django 3.2.4 on 2021-06-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0004_auto_20210609_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winner',
            name='winner',
        ),
        migrations.AlterField(
            model_name='winner',
            name='draw_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
