# Generated by Django 3.2.4 on 2021-06-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0005_auto_20210609_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='w11',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='w12',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='winner',
            name='w13',
            field=models.IntegerField(null=True),
        ),
    ]
