# Generated by Django 3.2.4 on 2021-06-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfservice', '0006_auto_20210609_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='winner',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
